### ISSUE TITLE
"session" service is deprecated

### ISSUE THREAD

**Issue by yann-eugone** [sonata-project/twig-extensions#220]
## Feature Request

Looks like [FlashManager](https://github.com/sonata-project/twig-extensions/blob/master/src/FlashMessage/FlashManager.php) is not Symfony 5.3 ready.

Spotted during automated tests :

```
Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "sonata.twig.flashmessage.manager" service.
```

-----

If this is something you are interested with, I can create a PR :  

I would replace session dependency with `RequestStack`, and get session from main request (or master, depending on Symfony's version) in the `getSession` method.

**Comment by franmomu** [comment]
> If this is something you are interested with, I can create a PR

sure! it would be great, thank you!

**Comment by VincentLanglet** [comment]
In order to be BC, he has to support both Session and RequestStack as first param of the constructor. And we will remove the Session support in next major.
